Update check_qnap
nicht vorhandene Festplatten beim Temperaturcheck werden nun erkannt

diff --git a/check_qnap b/check_qnap
--- a/check_qnap
+++ b/check_qnap
@@ -172,7 +172,10 @@ elif [ "$strpart" == "hd2temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.2 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD2 temperature="$TEMPHD"C|HDD2 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD2 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD2 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -193,7 +196,10 @@ elif [ "$strpart" == "hd3temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.3 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD3 temperature="$TEMPHD"C|HDD3 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD3 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD3 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -214,7 +220,10 @@ elif [ "$strpart" == "hd4temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.4 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD4 temperature="$TEMPHD"C|HDD4 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD4 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD4 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -235,7 +244,10 @@ elif [ "$strpart" == "hd5temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.5 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD5 temperature="$TEMPHD"C|HDD5 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD5 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD5 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -256,7 +268,10 @@ elif [ "$strpart" == "hd6temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.6 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD6 temperature="$TEMPHD"C|HDD6 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD6 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD6 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -277,7 +292,10 @@ elif [ "$strpart" == "hd7temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.7 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD7 temperature="$TEMPHD"C|HDD7 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD7 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD7 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -298,7 +316,10 @@ elif [ "$strpart" == "hd8temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.8 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD8 temperature="$TEMPHD"C|HDD8 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD8 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD8 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -319,7 +340,10 @@ elif [ "$strpart" == "hd9temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.9 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD9 temperature="$TEMPHD"C|HDD9 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD9 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD9 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -340,7 +364,10 @@ elif [ "$strpart" == "hd10temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.10 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD10 temperature="$TEMPHD"C|HDD108 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD10 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD10 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -361,7 +388,10 @@ elif [ "$strpart" == "hd11temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.11 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD11 temperature="$TEMPHD"C|HDD11 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD11 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD11 temperatur to high!: "$OUTPUT
             	exit 2
     	else
@@ -382,7 +412,10 @@ elif [ "$strpart" == "hd12temp" ]; then
     	TEMPHD=$(snmpget -v1 -c "$strCommunity" $strHostname 1.3.6.1.4.1.24681.1.2.11.1.3.12 | awk '{print $4}' | cut -c2-3)
 	OUTPUT="HDD12 temperature="$TEMPHD"C|HDD12 termperature="$TEMPHD"C;$strWarning;$strCritical;0;60"
 
-    	if [ "$TEMPHD" -ge "59" ]; then
+	if [ "$TEMPHD" == "--" ]; then
+		echo "HDD12 not found"
+		exit 2
+    	elif [ "$TEMPHD" -ge "59" ]; then
             	echo "HDD12 temperatur to high!: "$OUTPUT
             	exit 2
     	else
